config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts, path: 'tweets' do
    member do
      post :retweet
    end
  end

  resources :users

  resources :friendships, only: [:create]

  root "posts#index"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  scope :direct_friends, ->(user_id) { where user_id: user_id }
  scope :inverse_friends, ->(user_id) { where friend_id: user_id }
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { order(created_at: :desc) }

  belongs_to :user
  validates :text, presence: true, length: {minimum: 2, maximum: 140}
  belongs_to :parrent, class_name: 'Post'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :friendships

  has_attached_file :avatar, styles: { thumb: '100x100#', medium: '400x400>' }, :default_url => "/images/:style/darth_vader_dummy_avatar.jpg"
  validates_attachment :avatar, content_type: { content_type:['image/jpeg', 'image/gif', 'image/png'] },
  size: { less_than: 3.megabytes }

  def friends
    (Friendship.inverse_friends(id).map(&:user) + Friendship.direct_friends(id).map(&:friend)).uniq
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:avatar, :first_name, :last_name, :email, :password, :current_password) }
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.new
    @friendship.user = current_user
    @friendship.friend = User.find(params[:id])
    if @friendship.save
      flash[:success] = "User added as a friend!"
      redirect_to root_path
    else
      flash[:success] = "I have bad feeling about this"
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :fetch_tweets, only: [:index, :create, :retweet, :destroy]

  def index
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      respond_to do |format|
        format.json { render json: json_builder(@post.decorate), status: 201 }
      end
    else
      respond_to do |format|
        format.json { render json: @post.errors.to_json.titleize, status: 422 }
      end
    end
  end

  def retweet
    @post = Post.find(params[:id])
    @retweet = Post.new(parrent_id: @post.id, text: @post.text, user_id: current_user.id)
    if @retweet.save
      redirect_to posts_path
    else
      flash[:alert] = "Something went wrong. Please try again!"
      render :index
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    render :index
    flash[:success] = "Deleted successfully!"
  end

  private

  def json_builder(post)
    { id: post.id, post: post.text, published_at: post.published_at }
  end

  def fetch_tweets
    @tweets = current_user.posts.page(params[:page]).per(5)
    @tweets = PaginatingDecorator.decorate(@tweets)
  end

  def post_params
    params.require(:post).permit(:text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all - [current_user] # removing logged in user form the list of all users
  end

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.page(params[:page]).per(5)

    if @user == current_user
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
.navbar.navbar-default.navbar-fixed-bottom
  .collapse.navbar-collapse
    %p.text-center TwitterLike © #{Time.now.strftime "%Y"}

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "Home", posts_path
        - if user_signed_in?
          %li= link_to "All Users", users_path
      %ul.nav.navbar-nav.pull-right
        - if user_signed_in?
          %li
            = link_to edit_user_registration_path, title: 'Edit profile' do
              - if current_user.first_name && current_user.last_name
                = current_user.full_name
              - else
                = current_user.email
          %li= link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign in", new_user_session_path

app/views/layouts/_old_application.html.haml
!!!
%html
  %head
    %title TwitterLike
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header= render 'layouts/navigation'
    .container{:role => "main"}
      .row
        .col-md-6.col-md-offset-3
          = flash_messages
      = yield
    %footer.footer= render 'layouts/footer'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterLike</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="admin <%= controller_name + '_' + action_name %>">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 system-messages">
          <%= flash_messages %>
        </div>
      </div>
      <%= yield %>
    </div>
    <footer class="footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/posts/_new_tweet.html.haml
.row
  .col-md-10.col-md-offset-1
    = form_for @post, url: { action: "create" }, remote: true, html: { class: "form form-inline", id: "new-tweet-js" } do |f|
      %section.form-group= f.text_area :text, placeholder: "Tweet here!", size: "65x1", class: "form-control"
      = f.submit 'Tweet', class: "btn btn-primary"
      %span.label.label-info.label-js
    %hr/

app/views/posts/_user_friends.html.haml
.col-md-3.col-md-offset-1
  - unless current_user.friends.empty?
    %h3 Your friends
    .list-group
      - current_user.friends.each do |friend|
        = link_to user_path(friend.id), class: "list-group-item" do
          - if friend.first_name && friend.last_name
            = friend.full_name
          - else
            = friend.email
          %span.badge= friend.posts.count

app/views/posts/index.html.haml
.row
  .col-md-10.col-md-offset-1
    %h1
      = image_tag current_user.avatar.url(:thumb), class: 'img-circle'
      Hi
      %span.text-info= current_user.first_name
    %hr/
= render 'new_tweet'
.row
  .col-md-6.col-md-offset-1.tweets-js
    .alert.alert-warning.alert-js{style: 'display:none', role: 'alert'}
    - @tweets.each do |post|
      .post{ :class => (" post-retweeted" if post.parrent_id.present?) }
        %small
          = post.published_at
        %p
          = post.text
          - if post.parrent_id.present?
            %small.text-muted
              \...retweeted from #{link_to post.parrent.user.email, user_path(post.parrent.user)}
        -# .btn-group.btn-group-xs{:role => "group"}
        = link_to post_path(post), method: :delete, class: 'btn btn-default', data: { toggle: 'tooltip', placement: 'right', title: 'Delete tweet' } do
          %span.glyphicon.glyphicon-trash
    = paginate @tweets
  = render 'user_friends'

app/views/posts/show.html.haml
.row
  %h1= @post.title
  %p= @post.text
.row
  .btn-group.btn-group-xs{:role => "group"}
    = link_to "Edit", edit_post_path, class: "btn btn-default"
    = link_to "Delete", post_path(@post), method: :delete, class: "btn btn-default"

app/views/users/index.html.haml
.row
  .col-md-6.col-md-offset-1
    %h1 Users list
.row
  .col-md-6.col-md-offset-1
    %ul.list-group.list-all-users
      - @users.each do |user|
        %li.list-group-item
          = image_tag user.avatar.url(:thumb), size: '33', class: 'img-circle'
          = link_to user_path(user), class: 'user-link' do
            - if user.first_name && user.last_name
              = user.full_name
            - else
              = user.email
          %span.badge= user.posts.count
          = link_to "Add to friend", friendships_path(id: user.id), method: :post, class: 'btn btn-default btn-xs'

app/views/users/show.html.haml
.row
  .col-md-8.col-md-offset-1
    %h2
      = image_tag @user.avatar.url(:thumb), class: 'img-circle'
      You are waching
      %span.text-info
        - if @user.first_name && @user.last_name
          = @user.full_name
        - else
          = @user.email
      Tweets
    %hr/
.row
  .col-md-6.col-md-offset-1
    - @user.posts.each do |post|
      .post
        %small
          = post.created_at.strftime("%d %b %Y")
        %p= post.text
        %section= link_to "Retweet", retweet_post_path(post), method: :post
    = paginate @user_posts